# Generated by Django 3.1.4 on 2021-01-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20210108_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published']},
        ),
    ]
