# Generated by Django 3.1.4 on 2021-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20210111_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='idtechnology',
        ),
        migrations.AddField(
            model_name='post',
            name='idtechnology',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='wall.IdTechnology'),
        ),
    ]
