# Generated by Django 3.1.4 on 2021-01-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20210111_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idtechnology',
            field=models.ManyToManyField(max_length=100, null=True, to='wall.IdTechnology'),
        ),
    ]
