# Generated by Django 3.1.4 on 2021-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210106_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
