# Generated by Django 3.1.4 on 2021-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210106_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
