# Generated by Django 3.1.4 on 2021-01-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210108_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='middle_name',
        ),
    ]
