# Generated by Django 3.1.4 on 2021-01-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_usernet_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='profiles.Technology'),
        ),
    ]
