# Generated by Django 3.1.4 on 2021-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210108_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
