# Generated by Django 3.1.4 on 2021-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210108_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
