# Generated by Django 3.1.4 on 2021-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210108_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='users', to='profiles.Technology'),
        ),
    ]
